#!/bin/bash

if [ -z "${gcs_dest}" ]; then
  log "No GCS destination URL prefix defined. Not uploading the image."
  exit 0
fi

# If someone puts a single slash at the end of the destination URL prefix, do
# what they mean and don't gratuitously use a double slash.
gcs_dest=${gcs_dest%/}

log "Uploading image to \"${gcs_dest}/${tarball_name}\""
gsutil cp "${originaldir}/${tarball_name}" "${gcs_dest}/${tarball_name}"

if [ -z "${gce_project}" ]; then
  log "No GCE destination project defined. Not adding the image."
  exit 0
fi

# GCE image name is the tarball basename minus minor and patch versions
image_name="$distribution-$major_version-$codename-$image_name_suffix"

# Only set the description if it's not set yet
if ! [[ -v description ]]; then
  description="${lsb_description} built on ${build_date}"
fi

log "Adding image \"${image_name}\" to GCE project \"${gce_project}\""
gcutil --project="${gce_project}" addimage "${image_name}" \
  "${gcs_dest}/${tarball_name}" --description="${description}" \
  --preferred_kernel="${gce_kernel}"
