#!/bin/bash

# For the following, 0 = good
declare -i exit_status=0
declare -i move_s3_path=0

declare -r s3cfg="${HOME}/.s3cfg"

for var in EC2_ACCESS_KEY EC2_SECRET_KEY EC2_CERT EC2_PRIVATE_KEY \
    EC2_USER_ID EUCALYPTUS_CERT EC2_REGION S3_BUCKET CUSTOM_S3_PATH
do
    if [ -z "${!var}" ]
    then
        echo "  unset ${var}"
        if [[ "${var}" =~ S3_BUCKET|CUSTOM_S3_PATH ]]
        then
            move_s3_path=1
        else
            exit_status=1
        fi
    elif [[ "${var}" =~ EC2_CERT|EC2_PRIVATE_KEY|EUCALYPTUS_CERT ]]
    then
        if [ ! -f "${!var}" ]
        then
            echo "missing ${var}=${!var}"
            exit_status=1
        else
            echo "   good ${var}=${!var}"
        fi
    else
        echo "   good ${var}=${!var}"
    fi
done

if ! command -v s3cmd 1>/dev/null
then
    echo "s3cmd is not installed."
    move_s3_path=1
elif [ -f "${s3cfg}" ]
then
    if [ -n "${EC2_ACCESS_KEY}" ]
    then
        if ! grep -iq "^access_key\s*=\s*${EC2_ACCESS_KEY}\s*$" "${s3cfg}"
        then
            echo "EC2_ACCESS_KEY not found in ${s3cfg}"
            move_s3_path=1
        fi
    fi
    if [ -n "${EC2_SECRET_KEY}" ]
    then
        if ! grep -iq "^secret_key\s*=\s*${EC2_SECRET_KEY}\s*$" "${s3cfg}"
        then
            echo "EC2_SECRET_KEY not found in ${s3cfg}"
            move_s3_path=1
        fi
    fi
else
    echo "s3cmd is not configured."
    move_s3_path=1
fi

echo
if [ "${exit_status}" -ne 0 ]
then
    echo "Environment not ready."
elif [ "${move_s3_path}" -ne 0 ]
then
    echo "Essentials are in place. move-s3-path is unavailable."
else
    echo "All systems green."
fi
exit ${exit_status}
