#!/bin/bash

declare -i get_desc=${get_desc:0}

if [ "${get_desc}" -eq 1 ]
then
    echo "    $(basename ${BASH_SOURCE[0]}) Build a Amazon Machine Image"
    return
fi

function check_arg()
{
    local var_name="${1}"

    if [ -z "${!var_name}" ]
    then
        die "Variable \$${var_name} must be set!"
    fi
}

function test_file()
{
    local file_name="${1}"

    check_arg "${file_name}"

    if [ ! -f "${!file_name}" ]
    then
        die "Could not find \$${file_name} file ${!file_name}!"
    fi
}

# AMI details
ami_id=
name_suffix="$(date +%Y%m%d)"
description=
snapshot_id=
volume_id=
volume_size='1'
volume_inodes=
volume_type='ebs'
apt_mirrors='http://http.debian.net/debian'

# EC2 known regions
known_regions=('us-east-1')
known_regions+=('us-west-1')
known_regions+=('us-west-2')
known_regions+=('eu-west-1')
known_regions+=('ap-southeast-1')
known_regions+=('ap-southeast-2')
known_regions+=('ap-northeast-1')
known_regions+=('sa-east-1')
known_regions+=('us-gov-west-1')

# EC2 host info
virt=paravirtual
instance_id=
region=
target_region=
availability_zone=

# Build-time info
debootstrap_dir='/target'

# List of options for this subcommand
help="$(get_command_name)
This subcommand creates an Amazon EC2 AMI.

${txtund}Bootstrapping${txtdef}
    --virt VIRT [paravirtual|hvm]     Select virtualization type (${txtbld}${virt}${txtbld})
    --arch ARCH [i386|amd64]          Processor architecture of the image (${txtbld}${arch}${txtdef})
    --codename C [jessie|wheezy]      Debian release codename to bootstrap (${txtbld}${codename}${txtdef})
    --filesystem FS [ext2..4|xfs]     Filesystem of the root volume (${txtbld}${filesystem}${txtdef})
    --volume-size SIZE                Default size of the root volume in GB (${txtbld}${volume_size}${txtdef})
    --volume-inodes SIZE              Optionally set a custom inode count for ext2/3/4 volumes.
    --volume-type TYPE [instance|ebs] Set the root volume type (${txtbld}${volume_type}${txtdef})
    --plugin FILE                     Path to plugin script.
                                      Can be specified more than once.

    --timezone ZONE                   Standard timezone (${txtbld}${timezone}${txtdef})
    --locale LOCALE                   Standard locale (${txtbld}${locale}${txtdef})
    --charmap CHARMAP                 Standard charmap (${txtbld}${charmap}${txtdef})

    --debootstrap-dir DIR             Debootstrap directory (${txtbld}${debootstrap_dir}${txtdef})
                                      The created volume will be mounted
                                      at \$debootstrap_dir/\$volume_id.

    --name SUFFIX                     AMI name suffix (${txtbld}${name_suffix}${txtdef})
    --description DESC                Description of the AMI
    --apt-mirrors \"URL[ URL...]\"    APT mirror URLs, space-separated (${txtbld}${apt_mirrors}${txtdef})

${txtund}AWS${txtdef}
    --access-key ID                   AWS Access Key (${txtbld}\$EC2_ACCESS_KEY${txtdef})
    --secret-key KEY                  AWS Secret Key (${txtbld}\$EC2_SECRET_KEY${txtdef})

{txtund}instance-store requirements{txtdef}  (where '--volume-type instance' is requested)
    --user ID                         Your 12-digit AWS user ID
    --ec2cert CERT                    Path to the cloud certificate
    --cert CERT                       Path to your PEM-encoded certificate
    --private-key KEY                 Path to your PEM-encoded private key
    --s3-bucket BUCKET                S3 path to upload the image to
    --target-region REGION            AWS region to create image for

${txtund}Other options${txtdef}
    --debug                           Print debugging information
    --help                            Prints this help message
"

# Run through the parameters and save them to variables.
while [ ${#} -gt 0 ]
do
    case ${1} in
        --virt)             virt=${2};                     shift 2 ;;
        --arch)             arch=${2};                     shift 2 ;;
        --codename)         codename=${2};                 shift 2 ;;
        --filesystem)       filesystem=${2};               shift 2 ;;
        --volume-size)      volume_size=${2};              shift 2 ;;
        --volume-inodes)    volume_inodes=${2};            shift 2 ;;
        --volume-type)      volume_type=${2};              shift 2 ;;
        --name)             name_suffix=${2};              shift 2 ;;
        --description)      description=${2};              shift 2 ;;
        --apt-mirrors)      apt_mirrors=${2};              shift 2 ;;
        --access-key)       EC2_ACCESS_KEY=${2};           shift 2 ;;
        --secret-key)       EC2_SECRET_KEY=${2};           shift 2 ;;
        --user)             EC2_USER_ID=${2};              shift 2 ;;
        --ec2cert)          EUCALYPTUS_CERT=${2};          shift 2 ;;
        --cert)             EC2_CERT=${2};                 shift 2 ;;
        --private-key)      EC2_PRIVATE_KEY=${2};          shift 2 ;;
        --s3-bucket)        S3_BUCKET=${2};                shift 2 ;;
        --target-region)    target_region=${2};            shift 2 ;;
        --timezone)         timezone=${2};                 shift 2 ;;
        --locale)           locale=${2};                   shift 2 ;;
        --charmap)          charmap=${2};                  shift 2 ;;
        --debootstrap-dir)  debootstrap_dir=${2};          shift 2 ;;
        --plugin)           plugins+=("${2}");             shift 2 ;;
        --debug)            set -x;                        shift   ;;
        -h|--help)          printf -- "$help";             exit 0  ;;
        *)
            die "Unrecognized option: ${1}" \
                "Type '${0} --help' to see a list of possible options"; ;;
    esac
done

# Required and default parameters
check_arg EC2_ACCESS_KEY
check_arg EC2_SECRET_KEY

# Export the AWS access keys, so that we can launch euca2ools commands
# without specifying the keys as arguments each time.
export EC2_ACCESS_KEY EC2_SECRET_KEY

if [ "${volume_type}" = 'instance' ]
then
    check_arg EC2_USER_ID
    check_arg S3_BUCKET

    test_file EC2_PRIVATE_KEY
    test_file EC2_CERT
    test_file EUCALYPTUS_CERT

    export EC2_USER_ID S3_BUCKET EC2_PRIVATE_KEY EC2_CERT EUCALYPTUS_CERT
fi


# Specify points in the bootstrapping process, which the plugins can latch onto.
# This way plugins don't need fixing if we rename files.
TASK_PACKAGES="01-packages"
TASK_CREATE_VOLUME="10-create-volume"
TASK_MOUNT_VOLUME="13-mount-volume"
TASK_MOUNT_SPECIALS="15-mount-specials"
TASK_BOOTSTRAP="14-bootstrap"
TASK_APT_SOURCES="21-apt-sources"
TASK_APT_UPGRADE="22-apt-upgrade"
TASK_INITSCRIPTS="51-init-scripts"
TASK_UNMOUNT_SPECIALS="71-unmount-specials"
TASK_UNMOUNT_VOLUME="72-unmount-volume"
TASK_SNAPSHOT="80-ebs-snapshot"
TASK_DELETE_VOLUME="82-delete-volume"
TASK_CREATE_AMI="95-register-ami"
