#!/bin/bash
#
# Attach the EBS volume

declare -i attempt=12

# Get a random device letter, we will hang forever if we try to attach
# a volume to an already mapped device.
for device_letter in {f..z}
do
    device_path="/dev/xvd${device_letter}"
    [ ! -b ${device_path} ] && break
done
[ -b ${device_path} ] && \
    die "No free device letters found (tried xvdf to xvdz)!"

# The attach command fails in modern euca2ools versions when ran
# immediately after euca-create-volume - most probably because the
# command now executes too quickly for AWS's API to keep up!

while [ ${attempt} -ne 0 ] && \
    ! euca-describe-volumes "${volume_id}" 1>/dev/null 2>&1
do
    sleep 5
    (( --attempt ))
done

euca-attach-volume --instance "${instance_id}" \
    --device "/dev/xvd${device_letter}" "${volume_id}"

# Wait until the volume is attached
dotdot "test -b ${device_path} && echo attached"
