#!/bin/bash
#
# Configure GRUB as appropriate.

declare device_map
declare grub_device

# Disable the count-down.
sed -i "s/^GRUB_TIMEOUT=.*$/GRUB_TIMEOUT=0\nGRUB_HIDDEN_TIMEOUT=true/" \
    "${imagedir}/etc/default/grub"

# Disable recovery options - we won't be able to select them anyway.
sed -i "s/^#GRUB_DISABLE_RECOVERY=.*$/GRUB_DISABLE_RECOVERY=\"true\"/" \
    "${imagedir}/etc/default/grub"

# Set output console.
sed -i "s/^GRUB_CMDLINE_LINUX_DEFAULT=.*$/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet console=ttyS0 xen_emul_unplug=unnecessary\"/" \
    "${imagedir}/etc/default/grub"

if [ "${virt}" = "paravirtual" ]
then
    # Disable normal grub 2 cfg files
    chmod -x "${imagedir}"/etc/grub.d/*

    # Install the 40_custom file, which generates a nice menu.lst
    script='40_custom'
    cp "${scriptdir}/grub.d/${script}" "${imagedir}/etc/grub.d/${script}"
    chmod 755 "${imagedir}/etc/grub.d/${script}"

    # Update grub.cfg using the script
    chroot "${imagedir}" update-grub

    # pv-grub-hd0_1.04-x86_64.gz is configred for the old
    # (hd0)/boot/grub/menu.lst naming convention, but update-grub
    # names it /boot/grub/grub.cfg.
    chroot "${imagedir}" ln -s grub.cfg /boot/grub/menu.lst
else
    # Update grub.cfg using the script
    chroot "${imagedir}" update-grub

    device_map="${imagedir}/boot/grub/device.map"
    grub_device="$(grep "${device_path}$" "${device_map}" | cut -f 1)"

    # Update grub.cfg to use (hd0) instead of ${grub_device}.
    sed -i "s/${grub_device}/(hd0)/g" "${imagedir}/boot/grub/grub.cfg"

    chroot "${imagedir}" grub-install --no-floppy --recheck --force "${device_path}"
fi

# Remove everything from device.map after the first line (hd0).
sed -i '2,$d' "${device_map}"
