#!/bin/bash
#
# Adjust ec2-scripts as required by the instance type.

if [ "${virt}" = 'paravirtual' -a "${volume_type}" = 'instance' ]
then
    sed -i 's/^\(device_path\)=.*$/\1="\/dev\/xvda1"/' \
	"${imagedir}/etc/init.d/expand-volume"
fi
