#!/bin/bash
#
# Bundle of instance image

if [ "${volume_type}" = 'instance' ]
then
    bundledir="${debootstrap_dir}/${volume_id}-bundle"
    mkdir "${bundledir}"

    ami_name="${distribution}-${codename}-${arch}-${name_suffix}"

    b_arch="${arch}"
    if [ "${arch}" = "amd64" ]
    then
        b_arch="x86_64"
    fi

    euca-bundle-image -r "${b_arch}" -i "${image_file}" -d "${bundledir}" \
        -p "${ami_name}"
    if [ $? -ne 0 ]
    then
        die "Unable to bundle instance image."
    fi
fi
