#!/bin/bash

if [ "${volume_type}" = 'instance' ]
then
    if [ -n "${image_file}" ]
    then
        rm -f "${image_file}"
    else
        die "'${image_file}' not found - could not delete."
    fi
fi
