#!/bin/bash
#
# euca2ools conflicts with python-requests < 2, but may be installed
# by default on Wheezy as a cloud-init dependency. Fortunately 2.0.0
# is in wheezy-backports.


function install_euca2ools_deps {



    if [ "$(lsb_release -cs)" = "wheezy" ]
    then
        apt-get -y -t wheezy-backports install python-requests
    fi
}


# We're going to install euca2ools from source if they are not already
# present or are the wrong version. Make sure the dependencies are
# taken care of first.

if ! command -v euca-version > /dev/null 2>&1
then
    install_euca2ools_deps
elif [ $(euca-version 2>&1 | cut -d ' ' -f 2 | cut -b 1) -lt 3 ]
then
    install_euca2ools_deps
fi
